title: Curated Datasets
email:  Census.OpportunityProject@Census.gov
description: >-
  Discover issue-focused data recommended by government experts and test-driven by teams working to solve the nation’s biggest challenges.
baseurl: /data
url: "https://opportunity.census.gov"

# Configuration for Google Analytics, add your UA code here:
# google_analytics_ua: UA-????????-??

# Configuration for DAP, add your agency ID here:
# dap_agency: GSA

# Site Navigation
primary_navigation:
  - name: Main Website
    url: /

secondary_navigation:
  - name: Home
    url: /

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################


collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty


markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - .sass-cache
